-- Databricks notebook source
TRUNCATE TABLE SUPPLY_CHAIN.GOLD.T_PLANNERS;

INSERT INTO SUPPLY_CHAIN.GOLD.T_PLANNERS
WITH DATA_INGESTION AS (
    SELECT
        INGESTION_TIMESTAMP AS LAST_UPDATED_DATE,
        ACTIVE,
        MRP_CONTROLLER,
        PLANNER_NAME,
        PLANNER_EMAIL,
        PLANT,
        MANAGER,
        DIRECTOR
    FROM SUPPLY_CHAIN.SILVER.T_PLANNERS
        WHERE INGESTION_TIMESTAMP = (
            SELECT MAX(INGESTION_TIMESTAMP)
            FROM SUPPLY_CHAIN.SILVER.T_PLANNERS
    )
)

SELECT *
FROM DATA_INGESTION;

FROM SUPPLY_CHAIN.GOLD.T_PLANNERS
ORDER BY LAST_UPDATED_DATE DESC,
         MRP_CONTROLLER DESC;