-- Databricks notebook source
INSERT INTO SUPPLY_CHAIN.GOLD.T_DELFOR
WITH EKKO_EKPO_LFA1 AS (
    SELECT
        H.COMPANY_CODE,
        H.VENDOR_ID,
        LF.VENDOR_NAME,
        H.PO_DATE,
        H.PURCHASING_ORG,
        H.PURCHASING_GROUP,
        H.PO_DOCUMENT_TYPE,
        L.PO_NUMBER,
        L.PO_ITEM,
        L.MATERIAL_ID,
        L.PO_QUANTITY,
        L.BASE_UOM,
        L.PLANT,
        L.STORAGE_LOCATION,
        CAST(L.NET_PRICE AS DECIMAL(18,2)),
        CAST(L.PRICE_UNIT AS DECIMAL(18,2)),
        H.CURRENCY
                FROM SUPPLY_CHAIN.GOLD.T_EKPO L
                    LEFT JOIN SUPPLY_CHAIN.GOLD.T_EKKO H
                        ON H.PO_NUMBER = L.PO_NUMBER
                            LEFT JOIN SUPPLY_CHAIN.GOLD.T_LFA1 LF
                                ON H.VENDOR_ID = LF.VENDOR_ID
),

GR_CONFIRMATIONS AS (
    SELECT
        PO_NUMBER,
        PO_ITEM,
        SUM(QUANTITY) AS GR_QUANTITY
    FROM SUPPLY_CHAIN.GOLD.T_EKBE
    WHERE TRANSACTION_TYPE = 1 
    GROUP BY PO_NUMBER, PO_ITEM
),

 CONFIRMATIONS_HIERARCHY AS (
    SELECT
           *,
           ROW_NUMBER()
           OVER(
           PARTITION BY PO_NUMBER
           ORDER BY CONFIRMATION_SEQUENCE DESC) 
           RN
                FROM SUPPLY_CHAIN.GOLD.T_EKES
),

VENDOR_CONFIRMATIONS AS (
    SELECT
           *
            FROM CONFIRMATIONS_HIERARCHY
            WHERE RN = 1
),

PURCHASE_REQUESITIONS AS (
    SELECT
        *
            FROM SUPPLY_CHAIN.GOLD.T_EBAN
),

MATERIAL_MASTER_DATA AS (
        SELECT
            MATERIAL_ID,
            MATERIAL_DESCRIPTION,
            MATERIAL_TYPE,
            MATERIAL_GROUP
                FROM SUPPLY_CHAIN.GOLD.T_MARA
),

MRPC_DATA AS (
    SELECT
        MRP.MATERIAL_ID AS MATERIAL_ID,
        MRP.PLANT AS PLANT,
        MRP.MRP_CONTROLLER AS MRP_CONTROLLER,
        PL.PLANNER_NAME AS PLANNER_NAME,
        PL.ACTIVE AS ACTIVE,
        MRP.MINIMUM_LOT_SIZE AS MINIMUM_LOT_SIZE,
        MRP.MAXIMUM_LOT_SIZE AS MAXIMUM_LOT_SIZE
            FROM  SUPPLY_CHAIN.GOLD.T_MARC MRP
                LEFT JOIN SUPPLY_CHAIN.GOLD.T_PLANNERS PL
                    ON MRP.MRP_CONTROLLER = PL.MRP_CONTROLLER
),

JOINS AS (
    SELECT
        A.*,
        COALESCE(CAST(GR.GR_QUANTITY AS DECIMAL(18,2)),0) AS GR_QUANTITY,
        COALESCE(VC.CONFIRMATION_TYPE,'NC') AS LATEST_CONFIRMATION_TYPE,
        VC.CONFIRMATION_DATE AS LATEST_CONFIRMATION_DATE,
        VC.RN AS RN,
        PR.PR_NUMBER AS PR_NUMBER,
        PR.PR_ITEM AS PR_ITEM,
        PR.PR_DATE AS  PR_DATE,
        PR.REQUESTED_DELIVERY_DATE AS REQUESTED_DELIVERY_DATE,
        MMD.MATERIAL_TYPE,
        MMD.MATERIAL_DESCRIPTION,
        MMD.MATERIAL_GROUP,
        MMPL.MRP_CONTROLLER,
        MMPL.PLANNER_NAME,
        MMPL.MINIMUM_LOT_SIZE,
        MMPL.MAXIMUM_LOT_SIZE
            FROM EKKO_EKPO_LFA1 A -- <-- MAIN TABLE
                LEFT JOIN GR_CONFIRMATIONS GR
                    ON A.PO_NUMBER = GR.PO_NUMBER
                        AND A.PO_ITEM = GR.PO_ITEM
                            LEFT JOIN VENDOR_CONFIRMATIONS VC
                                 ON A.PO_NUMBER = VC.PO_NUMBER
                                    AND A.PO_ITEM = VC.PO_ITEM
                                        LEFT JOIN PURCHASE_REQUESITIONS PR
                                            ON A.PO_NUMBER = PR.PO_NUMBER
                                                AND A.PO_ITEM = PR.PO_ITEM
                                                    LEFT JOIN MATERIAL_MASTER_DATA MMD
                                                        ON A.MATERIAL_ID = MMD.MATERIAL_ID 
                                                            LEFT JOIN MRPC_DATA MMPL
                                                                ON MMPL.MATERIAL_ID = A.MATERIAL_ID
                                                                    AND MMPL.PLANT = A.PLANT 
                                                                        WHERE MMD.MATERIAL_TYPE = 'ROH' -- THIS FILTER BUSINESS SCOPE MATERIAL MANAGEMENT
),

CALCULATED_FIELDS AS (
    SELECT
            *,
            CONCAT(MATERIAL_ID,'-',MATERIAL_DESCRIPTION) AS MATERIAL_MATERIAL_DESCRIPTION,
            CAST((NET_PRICE*PRICE_UNIT)*PO_QUANTITY AS DECIMAL(18,2)) AS PO_VALUE,
            CAST(PO_QUANTITY-GR_QUANTITY AS DECIMAL(18,2)) AS PENDING_TO_GR,
            CAST((PO_QUANTITY-GR_QUANTITY)*(NET_PRICE*PRICE_UNIT) AS DECIMAL(18,2)) AS PENDING_TO_GR_VALUE,
            COALESCE(CAST(CAST(PO_QUANTITY-GR_QUANTITY AS DECIMAL(18,2))/PO_QUANTITY AS DECIMAL(4,2)),0.00) AS PENDING_TO_GR_PERCENTAGE,
            CAST(GR_QUANTITY/PO_QUANTITY AS DECIMAL (4,2)) AS GR_PERCENTAGE,
            CASE
                WHEN PENDING_TO_GR <= 0   THEN 'CLOSED'
                                           ELSE 'OPEN' END AS RECEIPT_STATUS,

            COALESCE(LATEST_CONFIRMATION_DATE,REQUESTED_DELIVERY_DATE) EXPECTED_DAY_TO_DELIVERY,
            DATEDIFF(COALESCE(LATEST_CONFIRMATION_DATE,REQUESTED_DELIVERY_DATE), CURRENT_DATE()) AS IN_DAYS_EXPECTED_DAY_TO_DELIVERY,
            CASE
                WHEN DATEDIFF(COALESCE(LATEST_CONFIRMATION_DATE,REQUESTED_DELIVERY_DATE),CURRENT_DATE()) >=11 AND  PENDING_TO_GR >0 THEN 'ON TIME'
                WHEN DATEDIFF(COALESCE(LATEST_CONFIRMATION_DATE,REQUESTED_DELIVERY_DATE),CURRENT_DATE()) >=6  AND  PENDING_TO_GR >0 THEN 'DUE IN 6-10 DAYS'
                WHEN DATEDIFF(COALESCE(LATEST_CONFIRMATION_DATE,REQUESTED_DELIVERY_DATE),CURRENT_DATE()) >1   AND  PENDING_TO_GR >0 THEN 'DUE IN 1-5 DAYS'
                WHEN DATEDIFF(COALESCE(LATEST_CONFIRMATION_DATE,REQUESTED_DELIVERY_DATE),CURRENT_DATE()) <0   AND  PENDING_TO_GR >0 THEN 'PAST DUE'
                                                                                                                                    ELSE 'FULLY RECEIVED'
                                                                                                                                    END AS_TODAY_DAY_TO_EXPECTED_DELIVERY_STATUS,
            COALESCE(LATEST_CONFIRMATION_DATE,REQUESTED_DELIVERY_DATE)+7 AS EXPECTED_INBOUND_AND_QA_TEST_COMPLETED,
            DATEDIFF(REQUESTED_DELIVERY_DATE, LATEST_CONFIRMATION_DATE) AS REQUESTED_VS_LASTEST_CONFIRMATION_DATE_DAYS
                FROM JOINS J
),

SELECTION AS (

    SELECT
        COMPANY_CODE,
        PURCHASING_ORG,
        PURCHASING_GROUP,
        PO_NUMBER,
        PO_ITEM,
        PO_DATE,
        PO_DOCUMENT_TYPE,
        VENDOR_ID,
        VENDOR_NAME,
        MRP_CONTROLLER,
        PLANNER_NAME,
        MATERIAL_ID,
        MATERIAL_DESCRIPTION,
        MATERIAL_MATERIAL_DESCRIPTION,
        MATERIAL_TYPE,
        MATERIAL_GROUP,
        NET_PRICE,
        PRICE_UNIT,
        BASE_UOM,
        MINIMUM_LOT_SIZE,
        MAXIMUM_LOT_SIZE,
        PO_VALUE,
        PO_QUANTITY,
        GR_QUANTITY,
        GR_PERCENTAGE,
        PENDING_TO_GR,
        PENDING_TO_GR_VALUE,
        PENDING_TO_GR_PERCENTAGE,
        RECEIPT_STATUS,
        PLANT,
        STORAGE_LOCATION,
        PR_NUMBER,
        PR_ITEM,
        PR_DATE,
        REQUESTED_DELIVERY_DATE,
        LATEST_CONFIRMATION_TYPE,
        LATEST_CONFIRMATION_DATE,
        EXPECTED_DAY_TO_DELIVERY,
        IN_DAYS_EXPECTED_DAY_TO_DELIVERY,
        AS_TODAY_DAY_TO_EXPECTED_DELIVERY_STATUS,
        EXPECTED_INBOUND_AND_QA_TEST_COMPLETED,
        REQUESTED_VS_LASTEST_CONFIRMATION_DATE_DAYS
        FROM CALCULATED_FIELDS
)

SELECT
    CURRENT_TIMESTAMP() AS SNAPSHOT,
    *
        FROM SELECTION;

    SELECT  -- DISPLAY RESULT WHEN RUN
        * 
            FROM SUPPLY_CHAIN.GOLD.T_DELFOR
                    ORDER BY SNAPSHOT DESC,
                        IN_DAYS_EXPECTED_DAY_TO_DELIVERY ASC;