-- Databricks notebook source
TRUNCATE TABLE SUPPLY_CHAIN.GOLD.T_EKBE;

INSERT INTO SUPPLY_CHAIN.GOLD.T_EKBE

WITH HIGHEST_REGISTER AS (SELECT 
            *,
            ROW_NUMBER()
            OVER(
            PARTITION BY PO_NUMBER, PO_ITEM,DOCUMENT_NUMBER
            ORDER BY INGESTION_TIMESTAMP DESC
            ) AS RN -- ROW_NUMBER IS USED TO RETAIN ALL TRANSACTIONS  (MULTIPLE GR & IR) FROM THE LATEST INGESTION FOR EACH PO AND ITEM
                 FROM SUPPLY_CHAIN.SILVER.T_EKBE)

    SELECT
        INGESTION_TIMESTAMP AS LAST_UPDATED_DATE,
        PO_NUMBER,
        PO_ITEM,
        DOCUMENT_NUMBER,
        FISCAL_YEAR,
        TRANSACTION_TYPE,
        POSTING_DATE,
        QUANTITY
           FROM  HIGHEST_REGISTER
                WHERE RN = 1;

SELECT
    *
FROM SUPPLY_CHAIN.GOLD.T_EKBE
ORDER BY LAST_UPDATED_DATE DESC,
         POSTING_DATE DESC,
         PO_NUMBER DESC,
         PO_ITEM DESC;