-- Databricks notebook source
TRUNCATE TABLE SUPPLY_CHAIN.GOLD.T_EKES;

INSERT INTO SUPPLY_CHAIN.GOLD.T_EKES

 WITH HIGHEST_REGISTER AS (SELECT 
            *,
            DENSE_RANK()
            OVER(
            PARTITION BY PO_NUMBER, PO_ITEM
            ORDER BY INGESTION_TIMESTAMP DESC
            ) AS RN -- DENSE_RANK RETAINS ALL CONFIRMATION TYPES FOR EACH PO AND ITEM FROM THE LATEST INGESTION, ASSIGNING RANK 1 TO ALL MATCHING RECORDS.
                 FROM SUPPLY_CHAIN.SILVER.T_EKES
    )

    SELECT
        INGESTION_TIMESTAMP AS LAST_UPDATED_DATE,
        PO_NUMBER,	
        PO_ITEM,
        CONFIRMATION_SEQUENCE,
        CONFIRMATION_TYPE,
        CONFIRMATION_DATE
           FROM  HIGHEST_REGISTER
                WHERE RN = 1;

SELECT
    *
FROM SUPPLY_CHAIN.GOLD.T_EKES
ORDER BY LAST_UPDATED_DATE DESC,
         PO_NUMBER DESC,
         PO_ITEM DESC;