-- Databricks notebook source
TRUNCATE TABLE SUPPLY_CHAIN.GOLD.T_LFA1;

INSERT INTO SUPPLY_CHAIN.GOLD.T_LFA1
WITH DATA_INGESTION AS (
    SELECT
        INGESTION_TIMESTAMP AS LAST_UPDATED_DATE,
        VENDOR_ID,
        VENDOR_NAME,
        COUNTRY,
        CITY,
        REGION,
        STREET,
        POSTAL_CODE
    FROM SUPPLY_CHAIN.SILVER.T_LFA1
        WHERE INGESTION_TIMESTAMP = (SELECT MAX(INGESTION_TIMESTAMP) FROM SUPPLY_CHAIN.SILVER.T_LFA1)
)

SELECT *
FROM DATA_INGESTION;

SELECT *
FROM SUPPLY_CHAIN.GOLD.T_LFA1
ORDER BY LAST_UPDATED_DATE DESC,
         VENDOR_ID DESC;