-- Databricks notebook source
TRUNCATE TABLE SUPPLY_CHAIN.GOLD.T_EBAN;

INSERT INTO SUPPLY_CHAIN.GOLD.T_EBAN
WITH HIGHEST_REGISTER AS (SELECT 
            *,
            ROW_NUMBER() 
            OVER(
            PARTITION BY PR_NUMBER, PR_ITEM
            ORDER BY INGESTION_TIMESTAMP DESC
            ) AS RN -- ROW_NUMBER ENSURES ONE RECORD PER PR AND ITEM, SELECTING THE LATEST INGESTION SINCE RAW HAS NO COLUMN TO TRACK MULTIPLE CHANGES WITHIN THE SAME DAY (ONE INGESTION PER DAY)
                 FROM SUPPLY_CHAIN.SILVER.T_EBAN)

    SELECT
        INGESTION_TIMESTAMP AS LAST_UPDATED_DATE,
        PR_NUMBER,	
        PR_ITEM,
        PO_NUMBER,	
        PO_ITEM,
        PR_DOCUMENT_TYPE,
        MATERIAL_ID,
        PR_QUANTITY,
        BASE_UOM,
        PLANT,	
        PR_DATE,	
        REQUESTED_DELIVERY_DATE,
        PURCHASING_GROUP
           FROM  HIGHEST_REGISTER
                WHERE RN = 1;

SELECT
    *
FROM SUPPLY_CHAIN.GOLD.T_EBAN
ORDER BY LAST_UPDATED_DATE DESC,
         PR_DATE DESC,
         PR_NUMBER DESC,
         PR_ITEM DESC;