-- Databricks notebook source
TRUNCATE TABLE SUPPLY_CHAIN.GOLD.T_MARC;

INSERT INTO SUPPLY_CHAIN.GOLD.T_MARC
WITH DATA_INGESTION AS (
    SELECT
        INGESTION_TIMESTAMP AS LAST_UPDATED_DATE,
        MATERIAL_ID,
        PLANT,
        MRP_TYPE,
        MRP_CONTROLLER,
        REORDER_POINT,
        SAFETY_STOCK,
        MINIMUM_LOT_SIZE,
        MAXIMUM_LOT_SIZE
    FROM SUPPLY_CHAIN.SILVER.T_MARC
        WHERE INGESTION_TIMESTAMP = (
            SELECT MAX(INGESTION_TIMESTAMP)
            FROM SUPPLY_CHAIN.SILVER.T_MARC
    )
)

SELECT *
FROM DATA_INGESTION;

SELECT *
FROM SUPPLY_CHAIN.GOLD.T_MARC
    ORDER BY LAST_UPDATED_DATE DESC,
             MATERIAL_ID DESC;