-- Databricks notebook source
TRUNCATE TABLE SUPPLY_CHAIN.GOLD.T_MARA;

INSERT INTO  SUPPLY_CHAIN.GOLD.T_MARA
WITH DATA_INGESTION AS (
    SELECT
        INGESTION_TIMESTAMP AS LAST_UPDATED_DATE,
        MATERIAL_ID,
        MATERIAL_DESCRIPTION,
        MATERIAL_TYPE,
        MATERIAL_GROUP,
        BASE_UOM,
        GROSS_WEIGHT,
        NET_WEIGHT,
        WEIGHT_UNIT,
        DIVISION
    FROM SUPPLY_CHAIN.SILVER.T_MARA
         WHERE INGESTION_TIMESTAMP = (
            SELECT MAX(INGESTION_TIMESTAMP)
            FROM SUPPLY_CHAIN.SILVER.T_MARA
    )

)
SELECT *
FROM DATA_INGESTION;

SELECT *
FROM SUPPLY_CHAIN.GOLD.T_MARA
ORDER BY LAST_UPDATED_DATE DESC,
         MATERIAL_ID DESC;