-- Databricks notebook source
TRUNCATE TABLE SUPPLY_CHAIN.GOLD.T_EKKO;

INSERT INTO SUPPLY_CHAIN.GOLD.T_EKKO
WITH HIGHEST_REGISTER AS (SELECT 
            *,
            ROW_NUMBER() 
            OVER(
            PARTITION BY PO_NUMBER
             ORDER BY INGESTION_TIMESTAMP DESC
             ) AS RN -- ROW_NUMBER ENSURES ONE RECORD PER PO, SELECTING THE LATEST INGESTION SINCE RAW HAS NO CHANGE DATE OR COLUMN TO TRACK MULTIPLE CHANGES WITHIN THE SAME DAY (ONE INGESTION PER DAY). 
                 FROM SUPPLY_CHAIN.SILVER.T_EKKO
)

SELECT
        INGESTION_TIMESTAMP AS LAST_UPDATED_DATE,
        PO_NUMBER,
        COMPANY_CODE,
        VENDOR_ID,
        PO_DATE,
        PURCHASING_ORG,
        PURCHASING_GROUP,
        CURRENCY,
        PO_DOCUMENT_TYPE
           FROM  HIGHEST_REGISTER
                WHERE RN = 1;

 SELECT
    *
FROM SUPPLY_CHAIN.GOLD.T_EKKO
ORDER BY LAST_UPDATED_DATE DESC,
         PO_DATE DESC,
         PO_NUMBER DESC;