-- Databricks notebook source
TRUNCATE TABLE SUPPLY_CHAIN.GOLD.T_EKPO;

INSERT INTO SUPPLY_CHAIN.GOLD.T_EKPO

WITH HIGHEST_REGISTER AS (SELECT 
            *,
            ROW_NUMBER()
            OVER(
            PARTITION BY PO_NUMBER, PO_ITEM
            ORDER BY INGESTION_TIMESTAMP DESC
            ) AS RN 
                 FROM SUPPLY_CHAIN.SILVER.T_EKPO
)

SELECT
        INGESTION_TIMESTAMP AS LAST_UPDATED_DATE,
        PO_NUMBER,
        PO_ITEM,
        MATERIAL_ID,
        PO_QUANTITY,
        BASE_UOM,
        PLANT,
        STORAGE_LOCATION,
        NET_PRICE,
        PRICE_UNIT
           FROM  HIGHEST_REGISTER
                WHERE RN = 1;


SELECT *
FROM SUPPLY_CHAIN.GOLD.T_EKPO
        ORDER BY LAST_UPDATED_DATE, PO_NUMBER, PO_ITEM DESC;