%sql
CREATE CATALOG IF NOT EXISTS SUPPLY_CHAIN;

CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN.BRONZE;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN.SILVER;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN.GOLD;

CREATE VOLUME IF NOT EXISTS SUPPLY_CHAIN.BRONZE.RAW_FILES;
