-- ============================================================================
-- FILE: 05_data_validation.sql
-- PROJECT: Supply Chain Analytics
--
-- DESCRIPTION:
-- Performs data quality and reconciliation checks across the Bronze, Silver
-- and Gold layers before the analytical model is consumed by Power BI.
--
-- VALIDATIONS:
-- - Row counts
-- - Duplicate business keys
-- - Null business keys
-- - CDC operation distribution
-- - Referential integrity
-- - Negative values
-- - Business-impact reconciliation
-- ============================================================================

-- ============================================================================
-- ROW COUNTS BY LAYER
-- ============================================================================

%sql
SELECT 'BRONZE.MATERIAL' AS TABLE_NAME, COUNT(*) AS TOTAL_ROWS
FROM SUPPLY_CHAIN.BRONZE.MATERIAL
UNION ALL
SELECT 'SILVER.MATERIAL_CDC', COUNT(*)
FROM SUPPLY_CHAIN.SILVER.MATERIAL_CDC
UNION ALL
SELECT 'GOLD.DIM_MATERIAL', COUNT(*)
FROM SUPPLY_CHAIN.GOLD.DIM_MATERIAL;

%sql
SELECT 'BRONZE.VENDOR' AS TABLE_NAME, COUNT(*) AS TOTAL_ROWS
FROM SUPPLY_CHAIN.BRONZE.VENDOR
UNION ALL
SELECT 'SILVER.VENDOR', COUNT(*)
FROM SUPPLY_CHAIN.SILVER.VENDOR
UNION ALL
SELECT 'GOLD.DIM_VENDOR', COUNT(*)
FROM SUPPLY_CHAIN.GOLD.DIM_VENDOR;

%sql
SELECT 'BRONZE.PURCHASE_ORDERS' AS TABLE_NAME, COUNT(*) AS TOTAL_ROWS
FROM SUPPLY_CHAIN.BRONZE.PURCHASE_ORDERS
UNION ALL
SELECT 'SILVER.PURCHASE_ORDERS', COUNT(*)
FROM SUPPLY_CHAIN.SILVER.PURCHASE_ORDERS
UNION ALL
SELECT 'GOLD.FACT_PROCUREMENT', COUNT(*)
FROM SUPPLY_CHAIN.GOLD.FACT_PROCUREMENT;

%sql
SELECT 'BRONZE.TRANSPORTATION' AS TABLE_NAME, COUNT(*) AS TOTAL_ROWS
FROM SUPPLY_CHAIN.BRONZE.TRANSPORTATION
UNION ALL
SELECT 'SILVER.TRANSPORTATION', COUNT(*)
FROM SUPPLY_CHAIN.SILVER.TRANSPORTATION
UNION ALL
SELECT 'GOLD.FACT_TRANSPORTATION', COUNT(*)
FROM SUPPLY_CHAIN.GOLD.FACT_TRANSPORTATION;

%sql
SELECT 'BRONZE.CUSTOMER' AS TABLE_NAME, COUNT(*) AS TOTAL_ROWS
FROM SUPPLY_CHAIN.BRONZE.CUSTOMER
UNION ALL
SELECT 'SILVER.CUSTOMER', COUNT(*)
FROM SUPPLY_CHAIN.SILVER.CUSTOMER
UNION ALL
SELECT 'GOLD.DIM_CUSTOMER', COUNT(*)
FROM SUPPLY_CHAIN.GOLD.DIM_CUSTOMER;

%sql
SELECT 'BRONZE.SALES' AS TABLE_NAME, COUNT(*) AS TOTAL_ROWS
FROM SUPPLY_CHAIN.BRONZE.SALES
UNION ALL
SELECT 'SILVER.SALES', COUNT(*)
FROM SUPPLY_CHAIN.SILVER.SALES
UNION ALL
SELECT 'GOLD.FACT_SALES', COUNT(*)
FROM SUPPLY_CHAIN.GOLD.FACT_SALES
UNION ALL
SELECT 'GOLD.FACT_BUSINESS_IMPACT', COUNT(*)
FROM SUPPLY_CHAIN.GOLD.FACT_BUSINESS_IMPACT;

-- ============================================================================
-- DUPLICATE BUSINESS KEYS
-- ============================================================================

%sql
SELECT
    MATERIAL_ID,
    COUNT(*) AS DUPLICATE_COUNT
FROM SUPPLY_CHAIN.GOLD.DIM_MATERIAL
GROUP BY MATERIAL_ID
HAVING COUNT(*) > 1;

%sql
SELECT
    VENDOR_ID,
    COUNT(*) AS DUPLICATE_COUNT
FROM SUPPLY_CHAIN.GOLD.DIM_VENDOR
GROUP BY VENDOR_ID
HAVING COUNT(*) > 1;

%sql
SELECT
    PO_ID,
    PO_LINE_ID,
    COUNT(*) AS DUPLICATE_COUNT
FROM SUPPLY_CHAIN.GOLD.FACT_PROCUREMENT
GROUP BY
    PO_ID,
    PO_LINE_ID
HAVING COUNT(*) > 1;

%sql
SELECT
    SHIPMENT_ID,
    COUNT(*) AS DUPLICATE_COUNT
FROM SUPPLY_CHAIN.GOLD.FACT_TRANSPORTATION
GROUP BY SHIPMENT_ID
HAVING COUNT(*) > 1;

%sql
SELECT
    CUSTOMER_ID,
    COUNT(*) AS DUPLICATE_COUNT
FROM SUPPLY_CHAIN.GOLD.DIM_CUSTOMER
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

%sql
SELECT
    SALES_ORDER_ID,
    SALES_LINE_ID,
    COUNT(*) AS DUPLICATE_COUNT
FROM SUPPLY_CHAIN.GOLD.FACT_SALES
GROUP BY
    SALES_ORDER_ID,
    SALES_LINE_ID
HAVING COUNT(*) > 1;

-- ============================================================================
-- NULL BUSINESS KEYS
-- ============================================================================

%sql
SELECT COUNT(*) AS NULL_MATERIAL_IDS
FROM SUPPLY_CHAIN.GOLD.DIM_MATERIAL
WHERE MATERIAL_ID IS NULL;

%sql
SELECT COUNT(*) AS NULL_VENDOR_IDS
FROM SUPPLY_CHAIN.GOLD.DIM_VENDOR
WHERE VENDOR_ID IS NULL;

%sql
SELECT COUNT(*) AS NULL_PURCHASE_ORDER_KEYS
FROM SUPPLY_CHAIN.GOLD.FACT_PROCUREMENT
WHERE PO_ID IS NULL
OR PO_LINE_ID IS NULL;

%sql
SELECT COUNT(*) AS NULL_SHIPMENT_IDS
FROM SUPPLY_CHAIN.GOLD.FACT_TRANSPORTATION
WHERE SHIPMENT_ID IS NULL;

%sql
SELECT COUNT(*) AS NULL_CUSTOMER_IDS
FROM SUPPLY_CHAIN.GOLD.DIM_CUSTOMER
WHERE CUSTOMER_ID IS NULL;

%sql
SELECT COUNT(*) AS NULL_SALES_KEYS
FROM SUPPLY_CHAIN.GOLD.FACT_SALES
WHERE SALES_ORDER_ID IS NULL
OR SALES_LINE_ID IS NULL;

-- ============================================================================
-- CDC OPERATION DISTRIBUTION
-- ============================================================================

%sql
SELECT
    CDC_OPERATION,
    COUNT(*) AS TOTAL_ROWS
FROM SUPPLY_CHAIN.SILVER.MATERIAL_CDC
GROUP BY CDC_OPERATION
ORDER BY CDC_OPERATION;

%sql
SELECT
    CDC_OPERATION,
    COUNT(*) AS TOTAL_ROWS
FROM SUPPLY_CHAIN.SILVER.PURCHASE_ORDERS
GROUP BY CDC_OPERATION
ORDER BY CDC_OPERATION;

%sql
SELECT
    CDC_OPERATION,
    COUNT(*) AS TOTAL_ROWS
FROM SUPPLY_CHAIN.SILVER.SALES
GROUP BY CDC_OPERATION
ORDER BY CDC_OPERATION;

-- ============================================================================
-- REFERENTIAL INTEGRITY
-- ============================================================================

%sql
SELECT COUNT(*) AS PROCUREMENT_WITHOUT_VENDOR
FROM SUPPLY_CHAIN.GOLD.FACT_PROCUREMENT P
LEFT JOIN SUPPLY_CHAIN.GOLD.DIM_VENDOR V
    ON P.VENDOR_ID = V.VENDOR_ID
WHERE V.VENDOR_ID IS NULL;

%sql
SELECT COUNT(*) AS PROCUREMENT_WITHOUT_MATERIAL
FROM SUPPLY_CHAIN.GOLD.FACT_PROCUREMENT P
LEFT JOIN SUPPLY_CHAIN.GOLD.DIM_MATERIAL M
    ON P.MATERIAL_ID = M.MATERIAL_ID
WHERE M.MATERIAL_ID IS NULL;

%sql
SELECT COUNT(*) AS SALES_WITHOUT_CUSTOMER
FROM SUPPLY_CHAIN.GOLD.FACT_SALES S
LEFT JOIN SUPPLY_CHAIN.GOLD.DIM_CUSTOMER C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;

%sql
SELECT COUNT(*) AS SALES_WITHOUT_MATERIAL
FROM SUPPLY_CHAIN.GOLD.FACT_SALES S
LEFT JOIN SUPPLY_CHAIN.GOLD.DIM_MATERIAL M
    ON S.MATERIAL_ID = M.MATERIAL_ID
WHERE M.MATERIAL_ID IS NULL;

-- ============================================================================
-- INVALID NUMERIC VALUES
-- ============================================================================

%sql
SELECT COUNT(*) AS INVALID_PROCUREMENT_ROWS
FROM SUPPLY_CHAIN.GOLD.FACT_PROCUREMENT
WHERE ORDER_QTY < 0
OR RECEIVED_QTY < 0
OR UNIT_PRICE < 0;

%sql
SELECT COUNT(*) AS INVALID_TRANSPORTATION_ROWS
FROM SUPPLY_CHAIN.GOLD.FACT_TRANSPORTATION
WHERE DISTANCE_KM < 0
OR FREIGHT_COST < 0;

%sql
SELECT COUNT(*) AS INVALID_SALES_ROWS
FROM SUPPLY_CHAIN.GOLD.FACT_SALES
WHERE QUANTITY < 0
OR UNIT_PRICE < 0
OR DISCOUNT < 0
OR SALES_AMOUNT < 0;

-- ============================================================================
-- BUSINESS IMPACT VALIDATION
-- ============================================================================

%sql
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT CONCAT(
        SALES_ORDER_ID,
        '-',
        SALES_LINE_ID
    )) AS UNIQUE_SALES_LINES,
    SUM(
        CASE
            WHEN GROSS_MARGIN < 0 THEN 1
            ELSE 0
        END
    ) AS NEGATIVE_MARGIN_ROWS,
    ROUND(AVG(MARGIN_PERCENT),2) AS AVG_MARGIN_PERCENT
FROM SUPPLY_CHAIN.GOLD.FACT_BUSINESS_IMPACT;

%sql
SELECT
    SALES_ORDER_ID,
    SALES_LINE_ID,
    CUSTOMER_NAME,
    MATERIAL_DESC,
    SALES_REVENUE,
    MATERIAL_COST,
    FREIGHT_COST,
    LANDED_COST,
    GROSS_MARGIN,
    MARGIN_PERCENT
FROM SUPPLY_CHAIN.GOLD.FACT_BUSINESS_IMPACT
WHERE GROSS_MARGIN < 0
ORDER BY GROSS_MARGIN ASC
LIMIT 100;

-- ============================================================================
-- SALES RECONCILIATION
-- ============================================================================

%sql
SELECT
    ROUND(SUM(SALES_AMOUNT),2) AS FACT_SALES_REVENUE
FROM SUPPLY_CHAIN.GOLD.FACT_SALES
WHERE ACTIVE_FLAG = 'Y';

%sql
SELECT
    ROUND(SUM(SALES_REVENUE),2) AS BUSINESS_IMPACT_REVENUE
FROM SUPPLY_CHAIN.GOLD.FACT_BUSINESS_IMPACT;

-- ============================================================================
-- COST RECONCILIATION
-- ============================================================================

%sql
SELECT
    ROUND(SUM(MATERIAL_COST),2) AS TOTAL_MATERIAL_COST,
    ROUND(SUM(FREIGHT_COST),2) AS TOTAL_FREIGHT_COST,
    ROUND(SUM(LANDED_COST),2) AS TOTAL_LANDED_COST
FROM SUPPLY_CHAIN.GOLD.FACT_COST_ANALYSIS;

%sql
SELECT
    ROUND(SUM(SALES_REVENUE),2) AS TOTAL_REVENUE,
    ROUND(SUM(MATERIAL_COST),2) AS TOTAL_MATERIAL_COST,
    ROUND(SUM(FREIGHT_COST),2) AS TOTAL_FREIGHT_COST,
    ROUND(SUM(LANDED_COST),2) AS TOTAL_LANDED_COST,
    ROUND(SUM(GROSS_MARGIN),2) AS TOTAL_GROSS_MARGIN
FROM SUPPLY_CHAIN.GOLD.FACT_BUSINESS_IMPACT;
