-- Databricks notebook source
INSERT INTO SUPPLY_CHAIN.SILVER.T_MARA
WITH DATA_INGESTION AS (
    SELECT
        INGESTION_DATE,
        INGESTION_TIMESTAMP,
        TRIM(MATNR) AS MATERIAL_ID,
        UPPER(TRIM(MAKTX)) AS MATERIAL_DESCRIPTION,
        UPPER(TRIM(MTART)) AS MATERIAL_TYPE,
        TRIM(MATKL) AS MATERIAL_GROUP,
        UPPER(TRIM(MEINS)) AS BASE_UOM,
        CAST(BRGEW AS DECIMAL(14,3)) AS GROSS_WEIGHT,
        CAST(NTGEW AS DECIMAL(14,3)) AS NET_WEIGHT,
        UPPER(TRIM(GEWEI)) AS WEIGHT_UNIT,
        TRIM(SPART) AS DIVISION
    FROM SUPPLY_CHAIN.BRONZE.T_MARA B
        WHERE INGESTION_TIMESTAMP = (
            SELECT MAX(INGESTION_TIMESTAMP)
            FROM SUPPLY_CHAIN.BRONZE.T_MARA
    )
)
SELECT *
FROM DATA_INGESTION;

SELECT *
FROM SUPPLY_CHAIN.SILVER.T_MARA
ORDER BY INGESTION_TIMESTAMP DESC,
         MATERIAL_ID DESC;