-- Databricks notebook source
INSERT INTO SUPPLY_CHAIN.SILVER.T_EKKO
WITH DATA_INGESTION AS (
    SELECT
        B.INGESTION_DATE AS INGESTION_DATE,
        B.INGESTION_TIMESTAMP AS INGESTION_TIMESTAMP,
        TRIM(B.EBELN) AS PO_NUMBER,
        TRIM(B.BUKRS) AS COMPANY_CODE,
        TRIM(B.LIFNR) AS VENDOR_ID,
        COALESCE(
            TRY_TO_DATE(B.BEDAT,'yyyy-MM-dd'),
            TRY_TO_DATE(B.BEDAT,'MM/dd/yyyy'),
            TRY_TO_DATE(B.BEDAT,'dd/MM/yyyy'),
            TRY_TO_DATE(B.BEDAT,'yyyy/MM/dd'),
            TRY_TO_DATE(B.BEDAT,'MM-dd-yyyy'),
            TRY_TO_DATE(B.BEDAT,'dd-MM-yyyy'),
            TRY_TO_DATE(B.BEDAT,'yyyyMMdd')
        ) AS PO_DATE,
        UPPER(TRIM(B.EKORG)) AS PURCHASING_ORG,
        UPPER(TRIM(B.EKGRP)) AS PURCHASING_GROUP,
        UPPER(TRIM(B.WAERS)) AS CURRENCY,
        UPPER(TRIM(B.BSART)) AS PO_DOCUMENT_TYPE
    FROM SUPPLY_CHAIN.BRONZE.T_EKKO B
    WHERE B.INGESTION_TIMESTAMP = (
        SELECT MAX(INGESTION_TIMESTAMP)
        FROM SUPPLY_CHAIN.BRONZE.T_EKKO
    )
)
SELECT *
FROM DATA_INGESTION;

SELECT *
FROM SUPPLY_CHAIN.SILVER.T_EKKO
ORDER BY INGESTION_TIMESTAMP DESC,
         PO_DATE DESC,
         PO_NUMBER DESC;