-- Databricks notebook source
INSERT INTO SUPPLY_CHAIN.SILVER.T_LFA1

WITH DATA_INGESTION AS (
    SELECT
    INGESTION_DATE,
    INGESTION_TIMESTAMP,
        TRIM(LIFNR) AS VENDOR_ID,
        UPPER(TRIM(NAME1)) AS VENDOR_NAME,
        UPPER(TRIM(LAND1)) AS COUNTRY,
        UPPER(TRIM(ORT01)) AS CITY,
        UPPER(TRIM(REGIO)) AS REGION,
        UPPER(TRIM(STRAS)) AS STREET,
        TRIM(PSTLZ) AS POSTAL_CODE
    FROM SUPPLY_CHAIN.BRONZE.T_LFA1 B
        WHERE INGESTION_TIMESTAMP = (SELECT MAX(INGESTION_TIMESTAMP) FROM SUPPLY_CHAIN.BRONZE.T_LFA1)
)
SELECT *
FROM DATA_INGESTION;

SELECT *
FROM SUPPLY_CHAIN.SILVER.T_LFA1
ORDER BY INGESTION_TIMESTAMP DESC,
         VENDOR_ID DESC;