-- Databricks notebook source
INSERT INTO SUPPLY_CHAIN.SILVER.T_EKPO
WITH DATA_INGESTION AS (
    SELECT
        B.INGESTION_DATE AS INGESTION_DATE,
        B.INGESTION_TIMESTAMP AS INGESTION_TIMESTAMP,
        TRIM(B.EBELN) AS PO_NUMBER,
        TRIM(B.EBELP) AS PO_ITEM,
        TRIM(B.MATNR) AS MATERIAL_ID,
        CAST(B.MENGE AS DECIMAL(14,3)) AS PO_QUANTITY,
        UPPER(TRIM(B.MEINS)) AS BASE_UOM,
        TRIM(B.WERKS) AS PLANT,
        TRIM(B.LGORT) AS STORAGE_LOCATION,
        CAST(B.NETPR AS DECIMAL(14,2)) AS NET_PRICE,
        CAST(B.PEINH AS DECIMAL(10,3)) AS PRICE_UNIT
    FROM SUPPLY_CHAIN.BRONZE.T_EKPO B
    WHERE B.INGESTION_TIMESTAMP = (
        SELECT MAX(INGESTION_TIMESTAMP)
        FROM SUPPLY_CHAIN.BRONZE.T_EKPO
    )
)
SELECT *
FROM DATA_INGESTION;

SELECT *
FROM SUPPLY_CHAIN.SILVER.T_EKPO
    ORDER BY INGESTION_TIMESTAMP, PO_NUMBER, PO_ITEM ASC;