-- Databricks notebook source
INSERT INTO SUPPLY_CHAIN.SILVER.T_MARC
WITH DATA_INGESTION AS (
    SELECT
         INGESTION_DATE,
        INGESTION_TIMESTAMP,
        TRIM(MATNR) AS MATERIAL_ID,
        TRIM(WERKS) AS PLANT,
        UPPER(TRIM(DISMM)) AS MRP_TYPE,
        TRIM(DISPO) AS MRP_CONTROLLER,
        CAST(MINBE AS DECIMAL(14,3)) AS REORDER_POINT,
        CAST(EISBE AS DECIMAL(14,3)) AS SAFETY_STOCK,
        CAST(BSTMI AS DECIMAL(14,3)) AS MINIMUM_LOT_SIZE,
        CAST(BSTMA AS DECIMAL(14,3)) AS MAXIMUM_LOT_SIZE
    FROM SUPPLY_CHAIN.BRONZE.T_MARC B
          WHERE INGESTION_TIMESTAMP = (
             SELECT MAX(INGESTION_TIMESTAMP)
             FROM SUPPLY_CHAIN.BRONZE.T_MARC
    )   
)

SELECT *
FROM DATA_INGESTION;

SELECT *
FROM SUPPLY_CHAIN.SILVER.T_MARC
        ORDER BY INGESTION_TIMESTAMP DESC,
                 MATERIAL_ID DESC ;