-- Databricks notebook source
INSERT INTO SUPPLY_CHAIN.SILVER.T_EBAN
WITH DATA_INGESTION AS (
    SELECT
        B.INGESTION_DATE AS INGESTION_DATE,
        B.INGESTION_TIMESTAMP AS INGESTION_TIMESTAMP,
        B.BANFN AS PR_NUMBER,
        B.BNFPO AS PR_ITEM,
        B.EBELN AS PO_NUMBER,
        B.EBELP AS PO_ITEM,
        UPPER(TRIM(B.BSART)) AS PR_DOCUMENT_TYPE,
        TRIM(B.MATNR) AS MATERIAL_ID,
        CAST(B.MENGE AS DECIMAL(14,3)) AS PR_QUANTITY,
        UPPER(TRIM(B.MEINS)) AS BASE_UOM,
        TRIM(B.WERKS) AS PLANT,
        COALESCE(TRY_TO_DATE(B.BADAT,'yyyyMMdd'),TRY_TO_DATE(B.BADAT,'yyyy-MM-dd')) AS PR_DATE,
        COALESCE(TRY_TO_DATE(B.LFDAT,'yyyyMMdd'),TRY_TO_DATE(B.LFDAT,'yyyy-MM-dd')) AS REQUESTED_DELIVERY_DATE,
        TRIM(B.EKGRP) AS PURCHASING_GROUP
    FROM SUPPLY_CHAIN.BRONZE.T_EBAN B
    WHERE B.INGESTION_TIMESTAMP = (
        SELECT MAX(INGESTION_TIMESTAMP)
        FROM SUPPLY_CHAIN.BRONZE.T_EBAN
    )
)
SELECT *
FROM DATA_INGESTION;

SELECT *
FROM SUPPLY_CHAIN.SILVER.T_EBAN
ORDER BY INGESTION_TIMESTAMP DESC,
         PR_DATE DESC,
         PR_NUMBER DESC,
         PR_ITEM DESC;