-- Databricks notebook source
INSERT INTO SUPPLY_CHAIN.SILVER.T_PLANNERS
WITH DATA_INGESTION AS (
    SELECT
        INGESTION_DATE,
        INGESTION_TIMESTAMP,
        TRIM(MRP_CONTROLLER) AS MRP_CONTROLLER,
        UPPER(TRIM(PLANNER_NAME)) AS PLANNER_NAME,
        UPPER(TRIM(PLANNER_EMAIL)) AS PLANNER_EMAIL,
        TRIM(PLANT) AS PLANT,
        UPPER(TRIM(ACTIVE)) AS ACTIVE,
        UPPER(TRIM(MANAGER)) AS MANAGER,
        UPPER(TRIM(DIRECTOR)) AS DIRECTOR
    FROM SUPPLY_CHAIN.BRONZE.T_PLANNERS B
        WHERE INGESTION_TIMESTAMP = (
            SELECT MAX(INGESTION_TIMESTAMP)
            FROM SUPPLY_CHAIN.BRONZE.T_PLANNERS
     )
)

SELECT *
FROM DATA_INGESTION;

FROM SUPPLY_CHAIN.SILVER.T_PLANNERS
ORDER BY INGESTION_TIMESTAMP DESC,
         MRP_CONTROLLER DESC;