-- Databricks notebook source
INSERT INTO SUPPLY_CHAIN.SILVER.T_EKBE
WITH DATA_INGESTION AS (
    SELECT
        B.INGESTION_DATE AS INGESTION_DATE,
        B.INGESTION_TIMESTAMP AS INGESTION_TIMESTAMP,
        TRIM(B.EBELN) AS PO_NUMBER,
        TRIM(B.EBELP) AS PO_ITEM,
        TRIM(B.BELNR) AS DOCUMENT_NUMBER,
        TRIM(B.GJAHR) AS FISCAL_YEAR,
        TRIM(B.VGABE) AS TRANSACTION_TYPE,
        COALESCE(TRY_TO_DATE(B.BUDAT,'yyyyMMdd'),TRY_TO_DATE(B.BUDAT,'yyyy-MM-dd')) AS POSTING_DATE,
        CAST(B.MENGE AS DECIMAL(14,3)) AS QUANTITY
    FROM SUPPLY_CHAIN.BRONZE.T_EKBE B
    WHERE B.INGESTION_TIMESTAMP = (
        SELECT MAX(INGESTION_TIMESTAMP)
        FROM SUPPLY_CHAIN.BRONZE.T_EKBE
    )
)
SELECT *
FROM DATA_INGESTION;

SELECT *
FROM SUPPLY_CHAIN.SILVER.T_EKBE
ORDER BY INGESTION_TIMESTAMP DESC,
         POSTING_DATE DESC,
         PO_NUMBER DESC,
         PO_ITEM DESC;