-- Databricks notebook source
INSERT INTO SUPPLY_CHAIN.SILVER.T_EKES
WITH DATA_INGESTION AS (
    SELECT
        B.INGESTION_DATE AS INGESTION_DATE,
        B.INGESTION_TIMESTAMP AS INGESTION_TIMESTAMP,
        TRIM(B.EBELN) AS PO_NUMBER,
        TRIM(B.EBELP) AS PO_ITEM,
        TRIM(B.ETENS) AS CONFIRMATION_SEQUENCE,
        UPPER(TRIM(B.EBTYP)) AS CONFIRMATION_TYPE,
        COALESCE(TRY_TO_DATE(B.EINDT,'yyyyMMdd'),TRY_TO_DATE(B.EINDT,'yyyy-MM-dd')) AS CONFIRMATION_DATE
    FROM SUPPLY_CHAIN.BRONZE.T_EKES B
    WHERE B.INGESTION_TIMESTAMP = (
        SELECT MAX(INGESTION_TIMESTAMP)
        FROM SUPPLY_CHAIN.BRONZE.T_EKES
    )
)
SELECT *
FROM DATA_INGESTION;

SELECT *
FROM SUPPLY_CHAIN.SILVER.T_EKES
ORDER BY INGESTION_TIMESTAMP DESC,
         PO_NUMBER DESC,
         PO_ITEM DESC;